spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.182.201:3306/paste?characterEncoding=UTF-8
    username: root
    password: sc100622

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    enabled: true
  aop:
    auto: true
